#strategies: alpha_beta, manual, min_max, random
#heuristics: dark_pieces_maximizing, light_pieces_maximizing, dark_pieces_light_pieces_difference, light_pieces_dark_pieces_difference

dark_player:
    strategy: alpha_beta
    heuristic: dark_pieces_maximizing
    depth: 1
light_player:
    strategy: manual
    heuristic: light_pieces_maximizing
    depth: 5